import Link from "next/link"
import { ArrowLeft, ArrowUpRight, Github } from "lucide-react"
import { PageTransitionLink } from "../page-transition-link"

const projects = [
  { title: "3D Model Market", type: "Web application", description: "A platform for buying and selling 3D models.", stack: ["Next.js", "TypeScript", "SQL Server"], status: "Selected work", video: "/projects/3d-model.mp4" },
  { title: "CineBook", type: "Web application", description: "A movie ticket booking platform with a focus on user experience.", stack: ["Next.js", "Tailwind", "MongoDB"], status: "Selected work", video: "/projects/cinebook-trim.mp4", caseStudy: "/projects/cinebook-case-study.pdf" },
  { title: "SlideMe", type: "Mobile application", description: "A mobile app for picking up and delivering your vehicles.", stack: ["React Native", "Javascript", "SQL Server"], status: "Selected work", video: "/projects/slideme.mp4", caseStudy: "/projects/slideme-case-study.pdf" },
]

export default function ProjectsPage() {
  return <main className="min-h-screen bg-background"><header className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6 lg:px-10"><PageTransitionLink href="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ArrowLeft size={16} /> Back to profile</PageTransitionLink><span className="font-mono text-xs tracking-[0.2em] text-primary">PROJECT INDEX / 03</span></header><section className="mx-auto max-w-6xl px-6 pb-24 pt-16 lg:px-10 lg:pt-28"><p className="font-mono text-xs uppercase tracking-[0.25em] text-primary">Selected projects</p><div className="mt-6 flex flex-col justify-between gap-8 border-b border-border pb-12 lg:flex-row lg:items-end"><h1 className="max-w-3xl text-balance text-5xl font-semibold leading-[1.05] tracking-[-0.05em] sm:text-7xl">Ideas, shaped into <span className="text-primary">working things.</span></h1><p className="max-w-xs text-sm leading-6 text-muted-foreground">A selection of products, experiments, and tools built with care.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{projects.map((project, index) => <article key={project.title} className="group flex min-h-[390px] flex-col rounded-[1.5rem] border border-border bg-card p-4 transition-colors hover:border-primary/60 sm:p-7"><div className="flex items-center justify-between px-3 pt-1 sm:px-0 sm:pt-0"><span className="font-mono text-xs text-primary">0{index + 1}</span><span className="text-xs text-muted-foreground">{project.status}</span></div><div className="mt-4 aspect-video overflow-hidden rounded-[1rem] bg-secondary"><video className="h-full w-full object-cover" src={project.video} autoPlay muted loop playsInline preload="metadata" aria-label={`${project.title} preview`} /></div><div className="mt-6"><p className="font-mono text-xs uppercase tracking-[0.16em] text-muted-foreground">{project.type}</p><h2 className="mt-3 text-2xl font-semibold tracking-tight">{project.title}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{project.description}</p><div className="mt-6 flex flex-wrap gap-2">{project.stack.map((tag) => <span key={tag} className="rounded-full bg-secondary px-2.5 py-1 text-xs text-secondary-foreground">{tag}</span>)}</div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3 border-t border-border pt-5 text-sm">{project.caseStudy && <a href={project.caseStudy} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-primary hover:underline">View case study <ArrowUpRight size={15} /></a>}<a href={project.video} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-primary hover:underline">Full video <ArrowUpRight size={15} /></a><a href="#" aria-label={`View ${project.title} source code`} className="text-muted-foreground hover:text-foreground"><Github size={17} /></a></div></div></article>)}</div></section></main>
}
